import { DeviceAvailabilityStatus } from "@/lib/enums/device-availability-status";
import { DeviceCategory } from "@/lib/enums/device-category";
import { DeviceConnectionStatus } from "@/lib/enums/device-connection-status";
import type { Device } from "@/lib/types/device";

export const DEVICE_FIXTURES = [
  {
    active: true,
    availability: DeviceAvailabilityStatus.Available,
    category: DeviceCategory.AudioInput,
    connection: DeviceConnectionStatus.Connected,
    default: true,
    enabled: true,
    id: "shure-mv7",
    muted: false,
    name: "Shure MV7",
    transport: "USB",
    volumePercent: 72,
  },
  {
    active: true,
    availability: DeviceAvailabilityStatus.Available,
    category: DeviceCategory.AudioOutput,
    connection: DeviceConnectionStatus.Connected,
    default: true,
    enabled: true,
    id: "studio-display",
    muted: false,
    name: "Studio Display",
    transport: "USB-C",
    volumePercent: 46,
  },
  {
    active: true,
    availability: DeviceAvailabilityStatus.Available,
    cameraResolution: "4K",
    cameraZoom: 1.15,
    category: DeviceCategory.Camera,
    connection: DeviceConnectionStatus.Connected,
    default: true,
    enabled: true,
    id: "logitech-brio",
    name: "Logitech Brio",
    transport: "USB",
  },
  {
    active: false,
    availability: DeviceAvailabilityStatus.Available,
    batteryPercent: 82,
    category: DeviceCategory.Keyboard,
    connection: DeviceConnectionStatus.Connected,
    default: false,
    enabled: true,
    id: "mx-mechanical",
    name: "MX Mechanical",
    transport: "Bluetooth",
  },
  {
    active: false,
    availability: DeviceAvailabilityStatus.Available,
    batteryPercent: 68,
    category: DeviceCategory.Mouse,
    connection: DeviceConnectionStatus.Connected,
    default: false,
    enabled: true,
    id: "mx-master-3s",
    name: "MX Master 3S",
    transport: "Bluetooth",
  },
  {
    active: false,
    availability: DeviceAvailabilityStatus.Unsupported,
    batteryPercent: 91,
    category: DeviceCategory.Trackpad,
    connection: DeviceConnectionStatus.Connected,
    default: false,
    enabled: true,
    id: "magic-trackpad",
    name: "Magic Trackpad",
    transport: "Bluetooth",
  },
] as const satisfies readonly Device[];
